
version: '2.2'
services:
   db:
     image: mysql
     container_name: db
     volumes:
       - db:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: Redhat123
       MYSQL_DATABASE: wordpress
       MYSQL_USER: usama
       MYSQL_PASSWORD: Redhat1234

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     mem_limit: 300m
     mem_reservation: 100m
     cpus: 0.5
     ports:
       - "8080:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: Redhat123

volumes:
   db: \{\}